### ISSUE TITLE
Handling hashes

### ISSUE THREAD

**Issue by goellner** [Yolk-HQ/next-routes#70]
It would be nice have support for hashes.

Something like this: 

```
<Link route={myRoute} params={myParams} hash={myHashValue}>
   ...
</Link>
```

There is an open issue on the source repo: https://github.com/fridays/next-routes/issues/165#issue-316936288

**Comment by goellner** [comment]
Maybe this pull request could be merged here:

https://github.com/fridays/next-routes/pull/258

**Comment by elliottsj** [comment]
This package is obsolete as of Next.js v9, since [dynamic routes are now natively supported](https://nextjs.org/blog/next-9#dynamic-route-segments).
