### ISSUE TITLE
About path string pattern

### ISSUE THREAD

**Issue by jasonyang-kk** [Yolk-HQ/next-routes#73]
There is a route like below 
```
add('/action/:param', 'action')
```
I only want a user enter action page with params, and other urls such as `/action` or `/action/` lead them to error page.
But right now, only `/action/` will go to the error page, the `/action` still routes to the 'action'.

Seems the path pattern didn't work.
Is there anyone know how to handle this kind of case?

**Comment by elliottsj** [comment]
This package is obsolete as of Next.js v9, since [dynamic routes are now natively supported](https://nextjs.org/blog/next-9#dynamic-route-segments).
